title: Binkley Papers
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - octopress-debugger
  - pry

#solr: http://localhost:8080/solr/select/?q=source%3Ahgww+AND+folder%3A1923&version=2.2&start=0&rows=25&wt=json&fl=id%2Ctitle%2Ccreator_exact%2Csummary%2Cnotes%2Cdate%2Cdate_certainty%2Cdate_precision%2Cdate_type%2Csource%2Cfolder%2Cpdfname%2Csubject%2Caddressee_exact
solr: http://localhost:8080/solr/select/?q=source%3A%22misc%22+AND+folder%3A%2269%22&version=2.2&start=0&rows=300&wt=json&fl=id%2Ctitle%2Csummary%2Cnotes%2Cdate%2Cdate_certainty%2Cdate_precision%2Cdate_type%2Csource%2Cfolder%2Cpdfname%2Csubject%2Ccorrespondent_exact
pdfroot: /home/pbinkley/Personal/digitization/rcb-fwb-pdfarchive
thumbroot: /home/pbinkley/Personal/digitization/rcb-fwb
facets:
  correspondents:
    field: correspondent_exact
    label: Corresponents
  subjects:
    field: subject
    label: Subjects

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
